CREATE TABLE IF NOT EXISTS agents(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    date_modified TIMESTAMP,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    agent_phone TEXT NOT NULL,
    agent_phone_type TEXT,
    agent_email TEXT NOT NULL,
    title TEXT,
    city TEXT,
    state TEXT,
    zip TEXT,
    office TEXT,
    bio TEXT,
    experience INTEGER,
    brokerage TEXT,
    slogan TEXT
);

